contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #somaticbmdata channel"
    url: https://nfcore.slack.com/channels/somaticbmdata
    about: Discussion about the nf-core/somaticbmdata pipeline
